from fpdf import FPDF
from ai_analyst.general_utils.file_utils import copy_files


def save_conversation_to_pdf(
        conversation_log, 
        pdf_path,
        font_path: str = "/kaggle/working/output/dejavusans-bold-ttf/DejaVuSans-Bold.ttf",
        ):
    pdf = FPDF()
    pdf.add_page()
    copy_files()
    
    # Add fonts
    pdf.add_font("DejaVu", "", font_path, uni=True)
    pdf.add_font("DejaVu", "B", font_path, uni=True)
    pdf.add_font("DejaVu", "I", font_path, uni=True)
    
    # Set colors
    pdf.set_text_color(0, 0, 0)  # Black text
    pdf.set_draw_color(200, 200, 200)  # Light gray for borders
    
    # Add title
    pdf.set_font("DejaVu", "B", 16)
    pdf.cell(0, 10, "Data Analysis Report", ln=True, align="C")
    pdf.ln(10)
    
    # Set default font for content
    pdf.set_font("DejaVu", "", 11)
    
    for kind, content in conversation_log:
        if kind == "TOOL_IMG":
            # Add a subtle border around images
            pdf.set_draw_color(200, 200, 200)
            pdf.rect(pdf.get_x(), pdf.get_y(), 180, 120)
            pdf.image(content, w=180)
            pdf.ln(5)
            continue
            
        if kind == "LLM":
            # Format LLM responses with indentation and proper spacing
            pdf.set_font("DejaVu", "", 11)
            pdf.multi_cell(0, 5, content)
            pdf.ln(5)
            
        elif kind == "TOOL_CODE":
            # Format code blocks with gray background
            pdf.set_fill_color(240, 240, 240)
            pdf.set_font("DejaVu", "", 10)
            pdf.multi_cell(0, 5, content, fill=True)
            pdf.ln(5)
            
        elif kind == "TOOL":
            # Format tool outputs with italic style
            pdf.set_font("DejaVu", "I", 10)
            pdf.multi_cell(0, 5, content)
            pdf.ln(5)
            
        elif kind == "DECIDER":
            # Format decider messages with bold style
            pdf.set_font("DejaVu", "B", 10)
            pdf.multi_cell(0, 5, f"Decision: {content}")
            pdf.ln(5)
            
        # Reset font for next iteration
        pdf.set_font("DejaVu", "", 11)
    
    # Add footer
    pdf.set_y(-15)
    pdf.set_font("DejaVu", "I", 8)
    pdf.cell(0, 10, f"Generated by AI Analyst", align="C")
    
    pdf.output(pdf_path)
    print(f"PDF saved → {pdf_path}")
